QUEUE_CLEARED = "The queue was cleared."
QUEUE_OPEN = "The queue is now open. Use !add XXX-XXX-XXX to submit your levels."
QUEUE_CLOSED = "The queue is now closed."
QUEUE_EMPTY = "The queue is empty!"
QUEUE_REMOVEDUSER = "Your level was removed from the queue."
PASTEBIN_FAILURE = "Error: Unable to create summary Pastebin."
WORDPRESS_FAILURE = "Error: Unable to post to website."
ERROR_BROADCASTER_COMMANDS = "Error processing broadcaster commands in the Mario Maker module."
ERROR_USER_COMMANDS = "Error processing user commands in the Mario Maker module."
ERROR_PLAYING_LEVEL_NOT_IN_QUEUE = "Error: Unable to play level not in queue. Verify the ID is valid."
ERROR_INVALID_SUBMISSION = "Error: Unable to add to or update the queue. Verify the ID is valid."

